// One-off seed script for the StoreItem catalog.
// Run with: npm run seed:store
//
// Uses upsert (findOneAndUpdate + upsert) rather than plain insertMany so
// this is safe to re-run after editing the catalog below.

import "dotenv/config";
import { connectDB, disconnectDB } from "../config/db.js";
import StoreItem from "../models/storeItemSchema.js";

const catalog = [
    { _id: "fire_emberbrand", name: "Emberbrand", description: "A bright coalition of will and heat that turns routine work into decisive action.", type: "power", school: "fire", costGold: 55, costGems: 0, icon: "🔥", rarity: "common", effectText: "+10% Fire XP on completed quests", effect: null },
    { _id: "fire_cinderstep", name: "Cinderstep", description: "A hot-footed spark that pushes you through the first hard minutes of momentum.", type: "power", school: "fire", costGold: 70, costGems: 0, icon: "🔥", rarity: "common", effectText: "+8% task streak momentum", effect: null },
    { _id: "fire_flameweaver", name: "Flameweaver", description: "The discipline of ignition. Adds a fierce edge to your hardest goals.", type: "power", school: "fire", costGold: 110, costGems: 0, icon: "🔥", rarity: "rare", effectText: "+18% Fire XP gain", effect: null },
    { _id: "fire_phoenixash", name: "Phoenix Ash", description: "The memory of rebirth preserved in a tiny ember of resilience.", type: "power", school: "fire", costGold: 140, costGems: 0, icon: "🔥", rarity: "rare", effectText: "Burst of extra gold for high-intensity sessions", effect: null },
    { _id: "fire_moltenrush", name: "Molten Rush", description: "A charged sprint that gives difficult objectives their first spark.", type: "power", school: "fire", costGold: 175, costGems: 10, icon: "🔥", rarity: "epic", effectText: "+25% task completion bonus", effect: null },
    { _id: "fire_sunforge", name: "Sunforge Arc", description: "A blazing sigil that rewards long-form endurance and focus.", type: "power", school: "fire", costGold: 210, costGems: 15, icon: "🔥", rarity: "epic", effectText: "+12% XP on deep-work sessions", effect: null },
    { _id: "fire_redline", name: "Redline Burst", description: "An urgent flare for your most important tasks and liftoff moments.", type: "power", school: "fire", costGold: 260, costGems: 18, icon: "🔥", rarity: "epic", effectText: "Prioritizes the highest-value quest", effect: null },
    { _id: "fire_ashenvow", name: "Ashen Vow", description: "Forged from recovered setbacks, it makes every retry more ferocious.", type: "power", school: "fire", costGold: 300, costGems: 22, icon: "🔥", rarity: "legendary", effectText: "Greatly boosts retry resilience", effect: null },
    { _id: "fire_siegeofdawn", name: "Siege of Dawn", description: "A radiant battle-chant that makes you lead before you feel ready.", type: "power", school: "fire", costGold: 350, costGems: 28, icon: "🔥", rarity: "legendary", effectText: "+30% Fire reward output", effect: null },
    { _id: "fire_embercrown", name: "Ember Crown", description: "The final fire-mark of a champion who converts effort into glow.", type: "power", school: "fire", costGold: 420, costGems: 35, icon: "🔥", rarity: "legendary", effectText: "Legendary fire mastery bonus", effect: null },

    { _id: "water_tidalbreath", name: "Tidal Breath", description: "A calm current that steadies your rhythm and keeps your energy flowing.", type: "power", school: "water", costGold: 55, costGems: 0, icon: "💧", rarity: "common", effectText: "+10% Water XP on sustainable habits", effect: null },
    { _id: "water_mooncurrent", name: "Mooncurrent", description: "A silver flow that balances obsession with recovery.", type: "power", school: "water", costGold: 75, costGems: 0, icon: "💧", rarity: "common", effectText: "+8% hydration and recovery bonus", effect: null },
    { _id: "water_deeppool", name: "Deep Pool", description: "A patient reservoir of calm that makes your routine feel effortless.", type: "power", school: "water", costGold: 110, costGems: 0, icon: "💧", rarity: "rare", effectText: "+18% Water XP gain", effect: null },
    { _id: "water_riverglass", name: "Riverglass", description: "An unbroken streak of clarity that smooths each decision.", type: "power", school: "water", costGold: 150, costGems: 4, icon: "💧", rarity: "rare", effectText: "+14% focus recovery", effect: null },
    { _id: "water_wavechain", name: "Wavechain", description: "Each task flows into the next with less friction and more depth.", type: "power", school: "water", costGold: 180, costGems: 10, icon: "💧", rarity: "epic", effectText: "+25% habit chaining bonus", effect: null },
    { _id: "water_aquabloom", name: "Aqua Bloom", description: "A nutritious current that rewards gentle consistency.", type: "power", school: "water", costGold: 210, costGems: 14, icon: "💧", rarity: "epic", effectText: "+12% recovery and health XP", effect: null },
    { _id: "water_mistcloak", name: "Mistcloak", description: "A soft veil that keeps your focus grounded under stress.", type: "power", school: "water", costGold: 255, costGems: 18, icon: "💧", rarity: "epic", effectText: "Reduces task feel-overwhelmed penalties", effect: null },
    { _id: "water_coralresonance", name: "Coral Resonance", description: "A living frequency that lets you sustain momentum without strain.", type: "power", school: "water", costGold: 305, costGems: 22, icon: "💧", rarity: "legendary", effectText: "Greatly improves cooldown recovery", effect: null },
    { _id: "water_floodstep", name: "Floodstep", description: "Your path becomes fluid, and progress becomes easy to continue.", type: "power", school: "water", costGold: 360, costGems: 28, icon: "💧", rarity: "legendary", effectText: "+30% Water reward output", effect: null },
    { _id: "water_glacierwhisper", name: "Glacier Whisper", description: "Silent and profound power that lets calm become a weapon.", type: "power", school: "water", costGold: 420, costGems: 35, icon: "💧", rarity: "legendary", effectText: "Legendary water mastery bonus", effect: null },

    { _id: "earth_stonewake", name: "Stonewake", description: "A grounded spark that anchors your strongest habits in place.", type: "power", school: "earth", costGold: 60, costGems: 0, icon: "🪨", rarity: "common", effectText: "+10% Earth XP on grounded tasks", effect: null },
    { _id: "earth_boulderheart", name: "Boulderheart", description: "An intentional weight and steadiness that keeps you from drifting.", type: "power", school: "earth", costGold: 80, costGems: 0, icon: "🪨", rarity: "common", effectText: "+8% consistency reward", effect: null },
    { _id: "earth_terravein", name: "Terra Vein", description: "The deep-rooted essence of quiet momentum and durable effort.", type: "power", school: "earth", costGold: 115, costGems: 0, icon: "🪨", rarity: "rare", effectText: "+18% Earth XP gain", effect: null },
    { _id: "earth_ironroot", name: "Ironroot", description: "A sturdy way to make your routine hold when life is loud.", type: "power", school: "earth", costGold: 150, costGems: 6, icon: "🪨", rarity: "rare", effectText: "+12% resilience on tough quests", effect: null },
    { _id: "earth_mountainhush", name: "Mountain Hush", description: "The calm stillness of a summit — deep focus without rush.", type: "power", school: "earth", costGold: 185, costGems: 10, icon: "🪨", rarity: "epic", effectText: "+25% deep-work completion bonus", effect: null },
    { _id: "earth_golemstep", name: "Golem Step", description: "Heavy-limbed certainty that carries you through difficult blocks.", type: "power", school: "earth", costGold: 220, costGems: 15, icon: "🪨", rarity: "epic", effectText: "+12% discipline bonus", effect: null },
    { _id: "earth_verdantanchor", name: "Verdant Anchor", description: "A rooted calm that helps strong routines survive intention drift.", type: "power", school: "earth", costGold: 260, costGems: 18, icon: "🪨", rarity: "epic", effectText: "Improves habit retention by +12%", effect: null },
    { _id: "earth_cragborn", name: "Cragborn", description: "A mountain-born will that rewards the brave and persistent.", type: "power", school: "earth", costGold: 310, costGems: 24, icon: "🪨", rarity: "legendary", effectText: "Greatly boosts physical discipline", effect: null },
    { _id: "earth_canyonecho", name: "Canyon Echo", description: "A resonant power that lets quiet persistence echo into results.", type: "power", school: "earth", costGold: 370, costGems: 30, icon: "🪨", rarity: "legendary", effectText: "+30% Earth reward output", effect: null },
    { _id: "earth_earthwake", name: "Earthwake", description: "Rises from the source of force itself and stabilizes your path.", type: "power", school: "earth", costGold: 430, costGems: 36, icon: "🪨", rarity: "legendary", effectText: "Legendary earth mastery bonus", effect: null },

    { _id: "air_galethread", name: "Gale Thread", description: "A quicksilver current that lets your ideas move with less friction.", type: "power", school: "air", costGold: 60, costGems: 0, icon: "🌬️", rarity: "common", effectText: "+10% Air XP on movement tasks", effect: null },
    { _id: "air_skycut", name: "Skycut", description: "A motion-rich power that makes plans feel lighter and sharper.", type: "power", school: "air", costGold: 80, costGems: 0, icon: "🌬️", rarity: "common", effectText: "+8% momentum bonus", effect: null },
    { _id: "air_tempestecho", name: "Tempest Echo", description: "A compressed storm of accelerated decisions and fast action.", type: "power", school: "air", costGold: 118, costGems: 0, icon: "🌬️", rarity: "rare", effectText: "+18% Air XP gain", effect: null },
    { _id: "air_zephyrsnap", name: "Zephyr Snap", description: "A crisp burst that helps you act when hesitation begins to form.", type: "power", school: "air", costGold: 154, costGems: 6, icon: "🌬️", rarity: "rare", effectText: "+12% task initiative boost", effect: null },
    { _id: "air_stormlattice", name: "Storm Lattice", description: "The structure of speed without chaos — controlled motion for real growth.", type: "power", school: "air", costGold: 188, costGems: 10, icon: "🌬️", rarity: "epic", effectText: "+25% movement-task reward", effect: null },
    { _id: "air_cloudstep", name: "Cloudstep", description: "A gentle lift that keeps you mentally untangled and quick.", type: "power", school: "air", costGold: 225, costGems: 15, icon: "🌬️", rarity: "epic", effectText: "+12% planning efficiency", effect: null },
    { _id: "air_riftrunner", name: "Rift Runner", description: "A sudden flash of motion that makes changes feel faster and smoother.", type: "power", school: "air", costGold: 267, costGems: 18, icon: "🌬️", rarity: "epic", effectText: "Improves habit switching speed", effect: null },
    { _id: "air_heliconline", name: "Heliocline", description: "A bright arc of acceleration that cuts through creative hesitation.", type: "power", school: "air", costGold: 315, costGems: 24, icon: "🌬️", rarity: "legendary", effectText: "Greatly boosts initiative", effect: null },
    { _id: "air_featherspear", name: "Feather Spear", description: "A sharp aerial insight that turns small experiments into breakthroughs.", type: "power", school: "air", costGold: 375, costGems: 30, icon: "🌬️", rarity: "legendary", effectText: "+30% Air reward output", effect: null },
    { _id: "air_cyclonehalo", name: "Cyclone Halo", description: "A radiant swirl that turns momentum into visible progress and confidence.", type: "power", school: "air", costGold: 440, costGems: 36, icon: "🌬️", rarity: "legendary", effectText: "Legendary air mastery bonus", effect: null },

    { _id: "arcane_prismsigil", name: "Prism Sigil", description: "A shimmering glyph that reveals hidden patterns in your effort.", type: "power", school: "arcane", costGold: 65, costGems: 0, icon: "🔮", rarity: "common", effectText: "+10% Arcane XP on clever tasks", effect: null },
    { _id: "arcane_astralthread", name: "Astral Thread", description: "Weaves a subtle sense of direction into your next move.", type: "power", school: "arcane", costGold: 85, costGems: 0, icon: "🔮", rarity: "common", effectText: "+8% insight reward", effect: null },
    { _id: "arcane_moonspell", name: "Moonspell", description: "A quiet oracle power that reveals the right next step.", type: "power", school: "arcane", costGold: 120, costGems: 0, icon: "🔮", rarity: "rare", effectText: "+18% Arcane XP gain", effect: null },
    { _id: "arcane_ciphergate", name: "Cipher Gate", description: "Unlocks clarity in the abstract and complexity in the ordinary.", type: "power", school: "arcane", costGold: 155, costGems: 6, icon: "🔮", rarity: "rare", effectText: "+12% problem-solving boost", effect: null },
    { _id: "arcane_arcrift", name: "Arc Rift", description: "A split in the fog of effort, revealing momentary brilliance.", type: "power", school: "arcane", costGold: 190, costGems: 10, icon: "🔮", rarity: "epic", effectText: "+25% analytical reward", effect: null },
    { _id: "arcane_runelantern", name: "Rune Lantern", description: "Illuminates the pathway to deeper focus and less confusion.", type: "power", school: "arcane", costGold: 230, costGems: 15, icon: "🔮", rarity: "epic", effectText: "+12% insight generation", effect: null },
    { _id: "arcane_starforged", name: "Starforged", description: "A cosmic spark for tasks that require finesse and vision.", type: "power", school: "arcane", costGold: 270, costGems: 18, icon: "🔮", rarity: "epic", effectText: "Improves strategy reward quality", effect: null },
    { _id: "arcane_echolens", name: "Echo Lens", description: "Lets your learning reflect back with more precision and power.", type: "power", school: "arcane", costGold: 320, costGems: 24, icon: "🔮", rarity: "legendary", effectText: "Greatly improves study outcomes", effect: null },
    { _id: "arcane_nullbloom", name: "Null Bloom", description: "A paradoxical bloom of genius that rewrites your best approach.", type: "power", school: "arcane", costGold: 380, costGems: 30, icon: "🔮", rarity: "legendary", effectText: "+30% Arcane reward output", effect: null },
    { _id: "arcane_mysticloop", name: "Mystic Loop", description: "An infinite spiral of perception that lifts all complex efforts.", type: "power", school: "arcane", costGold: 450, costGems: 38, icon: "🔮", rarity: "legendary", effectText: "Legendary arcane mastery bonus", effect: null },

    { _id: "shadow_nightshade", name: "Nightshade", description: "A sleek, hidden power for quiet execution and focused stealth.", type: "power", school: "shadow", costGold: 60, costGems: 0, icon: "🌑", rarity: "common", effectText: "+10% Shadow XP on subtle tasks", effect: null },
    { _id: "shadow_veilreap", name: "Veilreap", description: "Makes your work feel less exposed and more decisive.", type: "power", school: "shadow", costGold: 82, costGems: 0, icon: "🌑", rarity: "common", effectText: "+8% strategic reward", effect: null },
    { _id: "shadow_obsidiancowl", name: "Obsidian Cowl", description: "A shadowy internal armor that protects your resolve.", type: "power", school: "shadow", costGold: 120, costGems: 0, icon: "🌑", rarity: "rare", effectText: "+18% Shadow XP gain", effect: null },
    { _id: "shadow_smokespire", name: "Smokespire", description: "Creates concealment for your resistance and a route around delays.", type: "power", school: "shadow", costGold: 158, costGems: 6, icon: "🌑", rarity: "rare", effectText: "+12% stealth productivity", effect: null },
    { _id: "shadow_duskbloom", name: "Dusk Bloom", description: "A twilight force that makes difficult habits feel intentional.", type: "power", school: "shadow", costGold: 195, costGems: 10, icon: "🌑", rarity: "epic", effectText: "+25% low-energy bonus", effect: null },
    { _id: "shadow_nocturnevein", name: "Nocturne Vein", description: "The quiet rhythm of a late-night achiever, made visible and potent.", type: "power", school: "shadow", costGold: 235, costGems: 15, icon: "🌑", rarity: "epic", effectText: "+12% late-session output", effect: null },
    { _id: "shadow_hollowmirror", name: "Hollow Mirror", description: "Reflects your best habits back at you with almost no friction.", type: "power", school: "shadow", costGold: 275, costGems: 18, icon: "🌑", rarity: "epic", effectText: "Improves self-accountability rewards", effect: null },
    { _id: "shadow_shadethorn", name: "Shade Thorn", description: "Sharpens your edge when you’re trying to become harder to distract.", type: "power", school: "shadow", costGold: 325, costGems: 24, icon: "🌑", rarity: "legendary", effectText: "Greatly boosts focus under pressure", effect: null },
    { _id: "shadow_gravelantern", name: "Grave Lantern", description: "A rare lantern of relentlessness for your fullest cycle of growth.", type: "power", school: "shadow", costGold: 390, costGems: 30, icon: "🌑", rarity: "legendary", effectText: "+30% Shadow reward output", effect: null },
    { _id: "shadow_eclipsedstep", name: "Eclipsed Step", description: "An all-consuming stealth of mastery that keeps your momentum hidden but real.", type: "power", school: "shadow", costGold: 460, costGems: 40, icon: "🌑", rarity: "legendary", effectText: "Legendary shadow mastery bonus", effect: null },

    { _id: "holy_dawnhalo", name: "Dawn Halo", description: "A radiant but grounded blessing that lifts your next action with moral clarity.", type: "power", school: "holy", costGold: 62, costGems: 0, icon: "✨", rarity: "common", effectText: "+10% Holy XP on meaningful tasks", effect: null },
    { _id: "holy_radiantcrest", name: "Radiant Crest", description: "A simple glow that turns intention into visible consistency.", type: "power", school: "holy", costGold: 86, costGems: 0, icon: "✨", rarity: "common", effectText: "+8% purpose reward", effect: null },
    { _id: "holy_sanctumbell", name: "Sanctum Bell", description: "A call to meaning; it makes each completed task echo loudly.", type: "power", school: "holy", costGold: 122, costGems: 0, icon: "✨", rarity: "rare", effectText: "+18% Holy XP gain", effect: null },
    { _id: "holy_aegisgrace", name: "Aegis Grace", description: "The feel of protection and steadiness when challenge arrives.", type: "power", school: "holy", costGold: 160, costGems: 6, icon: "✨", rarity: "rare", effectText: "+12% resilience reward", effect: null },
    { _id: "holy_solsticepalm", name: "Solstice Palm", description: "A warm open hand that invites you to keep moving without fear.", type: "power", school: "holy", costGold: 198, costGems: 12, icon: "✨", rarity: "epic", effectText: "+25% confidence reward", effect: null },
    { _id: "holy_seraphicward", name: "Seraphic Ward", description: "Holds your courage together when your system is under pressure.", type: "power", school: "holy", costGold: 238, costGems: 15, icon: "✨", rarity: "epic", effectText: "+12% protective bonus", effect: null },
    { _id: "holy_haloribbon", name: "Halo Ribbon", description: "A soft sign of worth that encourages courageous repetition.", type: "power", school: "holy", costGold: 280, costGems: 18, icon: "✨", rarity: "epic", effectText: "Improves habit confidence", effect: null },
    { _id: "holy_goldmere", name: "Goldmere", description: "A radiant vessel of value that increases your reward sense.", type: "power", school: "holy", costGold: 332, costGems: 24, icon: "✨", rarity: "legendary", effectText: "Greatly boosts reward appreciation", effect: null },
    { _id: "holy_lumenmark", name: "Lumenmark", description: "The proof of alignment between effort, purpose, and visible results.", type: "power", school: "holy", costGold: 395, costGems: 30, icon: "✨", rarity: "legendary", effectText: "+30% Holy reward output", effect: null },
    { _id: "holy_celestialguard", name: "Celestial Guard", description: "A bright monument of courage that keeps your spirit unwavering.", type: "power", school: "holy", costGold: 470, costGems: 40, icon: "✨", rarity: "legendary", effectText: "Legendary holy mastery bonus", effect: null },

    { _id: "nature_wildroot", name: "Wildroot", description: "A living vessel of calm momentum and organic persistence.", type: "power", school: "nature", costGold: 62, costGems: 0, icon: "🌿", rarity: "common", effectText: "+10% Nature XP on all tasks", effect: null },
    { _id: "nature_briarcharm", name: "Briar Charm", description: "A small green pulse that keeps your routine resilient and alive.", type: "power", school: "nature", costGold: 85, costGems: 0, icon: "🌿", rarity: "common", effectText: "+8% routine reward", effect: null },
    { _id: "nature_mossstep", name: "Mossstep", description: "A soft, durable rhythm that never lets your progress erode.", type: "power", school: "nature", costGold: 122, costGems: 0, icon: "🌿", rarity: "rare", effectText: "+18% Nature XP gain", effect: null },
    { _id: "nature_grovecall", name: "Grovecall", description: "A living invitation to keep returning with gentleness and force.", type: "power", school: "nature", costGold: 160, costGems: 6, icon: "🌿", rarity: "rare", effectText: "+12% continuity bonus", effect: null },
    { _id: "nature_sunfern", name: "Sunfern Crown", description: "Allows your effort to grow naturally in bright conditions.", type: "power", school: "nature", costGold: 200, costGems: 12, icon: "🌿", rarity: "epic", effectText: "+25% environmental reward", effect: null },
    { _id: "nature_bloomwake", name: "Bloomwake", description: "A spring-like call that makes your habits grow with joy.", type: "power", school: "nature", costGold: 240, costGems: 15, icon: "🌿", rarity: "epic", effectText: "+12% growth bonus", effect: null },
    { _id: "nature_thornshield", name: "Thornshield", description: "A protective, steady bloom that make progress feel safe.", type: "power", school: "nature", costGold: 282, costGems: 18, icon: "🌿", rarity: "epic", effectText: "Improves protection against drift", effect: null },
    { _id: "nature_rootkind", name: "Rootkind", description: "A deep-earth intelligence that turns small actions into long roots.", type: "power", school: "nature", costGold: 335, costGems: 24, icon: "🌿", rarity: "legendary", effectText: "Greatly improves compound progress", effect: null },
    { _id: "nature_canopysong", name: "Canopy Song", description: "The harmony of your habits growing together into a full ecosystem.", type: "power", school: "nature", costGold: 395, costGems: 30, icon: "🌿", rarity: "legendary", effectText: "+30% Nature reward output", effect: null },
    { _id: "nature_meadowpulse", name: "Meadow Pulse", description: "An alive and beautiful rhythm that keeps your efforts thriving.", type: "power", school: "nature", costGold: 470, costGems: 40, icon: "🌿", rarity: "legendary", effectText: "Legendary nature mastery bonus", effect: null },

    { _id: "mind_quietlogic", name: "Quiet Logic", description: "A mental lens for thinking more clearly and acting with less noise.", type: "power", school: "mind", costGold: 62, costGems: 0, icon: "🧠", rarity: "common", effectText: "+10% Mind XP on thoughtful tasks", effect: null },
    { _id: "mind_focusmirror", name: "Focus Mirror", description: "Reflects your attention back into the exact right work.", type: "power", school: "mind", costGold: 86, costGems: 0, icon: "🧠", rarity: "common", effectText: "+8% concentration reward", effect: null },
    { _id: "mind_thoughtthread", name: "Thought Thread", description: "Lets your ideas connect in a clear line of action.", type: "power", school: "mind", costGold: 122, costGems: 0, icon: "🧠", rarity: "rare", effectText: "+18% Mind XP gain", effect: null },
    { _id: "mind_calmcircuit", name: "Calm Circuit", description: "A stable, low-noise mental state that helps tasks feel possible.", type: "power", school: "mind", costGold: 160, costGems: 6, icon: "🧠", rarity: "rare", effectText: "+12% clarity reward", effect: null },
    { _id: "mind_insightlantern", name: "Insight Lantern", description: "The power to notice what matters and act without panic.", type: "power", school: "mind", costGold: 200, costGems: 12, icon: "🧠", rarity: "epic", effectText: "+25% reasoning reward", effect: null },
    { _id: "mind_innerprism", name: "Inner Prism", description: "A rainbow of cognitive sharpness that refracts complexity into solutions.", type: "power", school: "mind", costGold: 238, costGems: 15, icon: "🧠", rarity: "epic", effectText: "+12% learning growth", effect: null },
    { _id: "mind_mindecho", name: "Mind Echo", description: "A loop of insight that keeps your best ideas alive and actionable.", type: "power", school: "mind", costGold: 282, costGems: 18, icon: "🧠", rarity: "epic", effectText: "Improves recall and effort quality", effect: null },
    { _id: "mind_synapsebloom", name: "Synapse Bloom", description: "A neural bloom of confidence and deep processing.", type: "power", school: "mind", costGold: 336, costGems: 24, icon: "🧠", rarity: "legendary", effectText: "Greatly boosts cognitive rewards", effect: null },
    { _id: "mind_stillfiremind", name: "Stillfire Mind", description: "The cool center of a decisive and powerful intellect.", type: "power", school: "mind", costGold: 400, costGems: 30, icon: "🧠", rarity: "legendary", effectText: "+30% Mind reward output", effect: null },
    { _id: "mind_sapphirefocus", name: "Sapphire Focus", description: "An expansive clarity that turns effort into lasting mastery.", type: "power", school: "mind", costGold: 480, costGems: 40, icon: "🧠", rarity: "legendary", effectText: "Legendary mind mastery bonus", effect: null },

    { _id: "time_chronothread", name: "Chrono Thread", description: "A thin but powerful line of precision that helps you act at the right moment.", type: "power", school: "time", costGold: 62, costGems: 0, icon: "⏳", rarity: "common", effectText: "+10% Time XP on long-term tasks", effect: null },
    { _id: "time_hourglassorbit", name: "Hourglass Orbit", description: "Rotates your energy around effort, making time feel usable.", type: "power", school: "time", costGold: 88, costGems: 0, icon: "⏳", rarity: "common", effectText: "+8% efficiency reward", effect: null },
    { _id: "time_pastglass", name: "Pastglass", description: "A clear, reflective power from your previous wins into your next move.", type: "power", school: "time", costGold: 124, costGems: 0, icon: "⏳", rarity: "rare", effectText: "+18% Time XP gain", effect: null },
    { _id: "time_futureloom", name: "Future Loom", description: "Builds a thread between today and tomorrow so the next step feels easier.", type: "power", school: "time", costGold: 162, costGems: 6, icon: "⏳", rarity: "rare", effectText: "+12% foresight reward", effect: null },
    { _id: "time_spiralclock", name: "Spiral Clock", description: "A cyclical rhythm that helps your effort compound more cleanly.", type: "power", school: "time", costGold: 205, costGems: 12, icon: "⏳", rarity: "epic", effectText: "+25% long-horizon reward", effect: null },
    { _id: "time_momentdancer", name: "Moment Dancer", description: "Moves between small tasks fluidly, turning friction into rhythm.", type: "power", school: "time", costGold: 245, costGems: 15, icon: "⏳", rarity: "epic", effectText: "+12% cadence bonus", effect: null },
    { _id: "time_ageglass", name: "Ageglass", description: "A tempered perception of time that turns effort into healthy momentum.", type: "power", school: "time", costGold: 290, costGems: 18, icon: "⏳", rarity: "epic", effectText: "Improves time management reward", effect: null },
    { _id: "time_riftwhorl", name: "Rift Whorl", description: "Spins your energy so each task lands at the perfect moment.", type: "power", school: "time", costGold: 345, costGems: 24, icon: "⏳", rarity: "legendary", effectText: "Greatly boosts strategic timing", effect: null },
    { _id: "time_timebell", name: "Time Bell", description: "An echoing reminder that your effort is accumulating in real time.", type: "power", school: "time", costGold: 410, costGems: 30, icon: "⏳", rarity: "legendary", effectText: "+30% Time reward output", effect: null },
    { _id: "time_eternalpulse", name: "Eternal Pulse", description: "The final cadence of mastery — durable, inevitable, and unbroken.", type: "power", school: "time", costGold: 490, costGems: 42, icon: "⏳", rarity: "legendary", effectText: "Legendary time mastery bonus", effect: null },
];

async function seed() {
    await connectDB();

    for (const item of catalog) {
        const { _id, ...fields } = item;
        await StoreItem.findOneAndUpdate(
            { _id },
            { _id, ...fields },
            { upsert: true, new: true, setDefaultsOnInsert: true }
        );
        console.log(`✓ Seeded: ${item.name} (${_id})`);
    }

    console.log(`\nDone — ${catalog.length} store items seeded.`);
    await disconnectDB();
    process.exit(0);
}

seed().catch((err) => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
});